version: '3.1'
services:
  frontend:
    image: frontend:0.1 
    ports:
      - "8081:8081"
    networks:
      - todo-network
    environment:
      - BACKEND_URL=backend

  todo-backend:
    image: backend:0.1 
    ports:
      - "8080:8080"
    networks:
      - todo-network
    depends_on:
      - database
    environment:
      - DATABASE_URL=database

  todo-database:
    image: database:0.1 
    ports:
      - "5432:5432"
    networks:
      - todo-network

networks:
  todo-network: {}